#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Jan 27 20:09:20 2022

simulate the series by conditional distribution of sigma'

@author: dliu
"""

import sys 
sys.path.append("..") 
import torch
import numpy as np
import matplotlib.pyplot as plt

from utils import get_dataset
from misc import parameters

device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
params = parameters(data_type='Saddle_high', n_trainset=20, kx=1, ks=10, x_lower_bound=-1, lr=5e-4)


data_test_pathes = params.data_pathes[params.n_trainset:params.n_trainset+1]

### load data
x_lower_bound = params.x_lower_bound
kx = params.kx
ks = params.ks
x1, x2, s1, s2, diff_x, diff_s, dt_x, dt_s = \
    get_dataset(data_test_pathes, x_lower_bound=x_lower_bound, kx=kx, ks=ks, resample=False)


### load model for ODE(x and sigma)
from model import model_f_saddle
model_f = model_f_saddle().to(device)
model_f.load_state_dict(torch.load(params.model_f_path))

### load model for std and mean
from model import model_std_mean_saddle
model_H = model_std_mean_saddle().to(device)
model_H.load_state_dict(torch.load(params.model_std_mean_path))

### load model for distribution of noise in sigma
from model import model_fs_dist_saddle
model_K = model_fs_dist_saddle().to(device)
model_K.load_state_dict(torch.load(params.model_dist_path))


def plot_x_s(t_series, x_series, s_series):
    plt.figure(figsize=[16,5])
    plt.subplot(1,2,1)
    plt.plot(t_series, x_series, linewidth=.6)#, label='$X$ generated by Euler method')
    plt.xlabel('t')
    plt.title('Generated $X$')
    # plt.plot(x1[:10000], label='x real')
    plt.subplot(1,2,2)
    plt.plot(t_series, s_series, linewidth=.6)#, label=r'$\bar{\sigma}$ generated by Euler method')
    plt.xlabel('t')
    # plt.legend()
    plt.title(r'Generated $\bar{\sigma}$')
    # plt.savefig('./figures/Saddle_simulation_E-MLP.png',bbox_inches='tight')

if __name__=="__main__":
    
    #########################################################################
    ##### simulation x with given initial condition and sigma bar ###########
    #########################################################################
    from simulate_tools import simulate_x_with_sigma
    idx_init, length = 0, 3000
    x_init, s_init = x1[idx_init], s1[idx_init]
    x_series, s_series, t_series, fx_series = simulate_x_with_sigma(model_f, x_init, s_init, dt_x, idx_init, s1, length)
    
    plt.figure(figsize=[16,5])
    plt.subplot(1,2,1)
    plt.plot(t_series, x_series, linewidth=.6, label='$X$ generated by Euler method')
    plt.plot(t_series, x1[idx_init:idx_init+length], linewidth=.6, label='$X$ numerical')
    mse1 = np.mean((x_series-x1[idx_init:idx_init+length])**2)
    plt.plot([], [], ' ', label="MSE={:.2e}".format(mse1))
    # plt.ylim(-1,1)
    plt.xlabel('t')
    plt.legend(loc='lower right')
    plt.subplot(1,2,2)
    plt.plot(t_series, fx_series, linewidth=.6, label="$X'$ generated by Euler method")
    plt.plot(t_series, diff_x[idx_init:idx_init+length], linewidth=.6, label="$X'$ numerical")
    # plt.plot(t_series, s1[idx_init:idx_init+length], linewidth=.6, label='$\sigma$ real')
    msef1 = np.mean((x_series-diff_x[idx_init:idx_init+length])**2)
    plt.plot([], [], ' ', label="MSE={:.2e}".format(msef1))
    # plt.ylim(-1.5,1)
    plt.xlabel('t')
    plt.legend(loc='lower right')
    # plt.savefig('./figures/Saddle_generate_x_by_given_sigma_E-MLP.png',bbox_inches='tight')
    
    ##############################
    ####### estimate E-MLP #######
    ##### for table in paper #####
    ##############################
    length = 600
    np.random.seed(1)
    init_idx = np.random.choice(np.arange(10000, x1.shape[0]-length),1000)

    mse1_list, msef1_list = [], []
    for i, idx in enumerate(init_idx):
        x_init, s_init = x1[idx], s1[idx]
        x_series, s_series, t_series, fx_series = simulate_x_with_sigma(model_f, x_init, s_init, dt_x, idx, s1, length)
        
        mse1 = np.average((x_series[:, 0]-x1[idx:idx+length, 0])**2)
        msef1 = np.average((fx_series[:, 0]-diff_x[idx:idx+length, 0])**2)
        
        mse1_list.append(mse1)
        msef1_list.append(msef1)
        
        print(i)

    print("MSE of X: {}".format(np.mean(mse1_list))) ##0.005005750444036425
    print("MSE of X': {}".format(np.mean(msef1_list))) ##0.002502816469516608
    
    
    
    #################################################################
    ###### simulate both x and s by E-MLP with Gaussian noise #######
    #################################################################
    from simulate_tools import simulate_xs_with_GNN
    length = 10000
    idx_init = 0
    dt = 0.001*ks
    
    fig, axes = plt.subplots(1,2,figsize=[16,4])
    for _ in range(3):
        x_init, s_init = [[0.9994]], [[0.503]]
        x_series, s_series, t_series = \
            simulate_xs_with_GNN(model_f, model_H, x_init, s_init, dt, length, stop_threshold=-1)
    
        axes[0].plot(t_series, x_series)
        axes[1].plot(t_series, s_series)
        
    axes[0].set_title('X')
    axes[1].set_title(r'$\bar{\sigma}$')
    # fig.savefig('./figures/Simuation_by_E-MLP_with_Gaussian_noise.png')



    ##################################################################
    ###### simulate both x and s by E-MLP with empirical noise #######
    ##################################################################
    from simulate_tools import simulate_xs_with_EN
    length = 10000
    idx_init = 0
    dt = 0.001*ks
    
    fig, axes = plt.subplots(1,2,figsize=[16,4])
    for _ in range(3):
        x_init, s_init = [[0.9994]], [[0.503]]
        x_series, s_series, t_series = \
            simulate_xs_with_EN(model_f, model_K, x_init, s_init, dt, length=length, stop_threshold=-1)
            
        axes[0].plot(t_series, x_series)
        axes[1].plot(t_series, s_series)
    
    axes[0].set_title('X')
    axes[1].set_title(r'$\bar{\sigma}$')
    # fig.savefig('./figures/Simuation_by_E-MLP_with_empirical_noise.png')
    
    
    ############ save data(high noise) ###############
    # np.save('./figures/Saddle_high_part.npy', np.c_[np.cumsum(dt_x), x1, s1])
    # SS = []   #for high noise [5,13,17,9,16,11]
    # for i, seed in enumerate([5,13,17,9,16,11]):
    #     np.random.seed(seed)
    #     x_init, s_init = [x1[idx_init]], [s1[idx_init]]
    #     x_series, s_series, t_series = \
    #         simulate_xs_with_EN(model_f, model_K, x_init, s_init, dt, length=length, stop_threshold=-1)

    #     SS.append(np.c_[t_series, x_series, s_series])
    #     plt.plot(t_series, x_series, label=seed)
    # plt.legend()
    # np.savez('./figures/Saddle_high_simulations.npz', *SS)
    
    
    ############ save data(low noise) ###############
    # np.save('./figures/Saddle_low_part.npy', np.c_[np.cumsum(dt_x), x1, s1])
    # length = 20000
    # dt = 0.001*ks
    # SS = []   #for low noise [5,13,17,9,16,11]
    # for i, seed in enumerate([5,13,17,9,16,11]):
    #     np.random.seed(seed)
    #     x_init, s_init = [x1[idx_init]], [s1[idx_init]]
    #     x_series, s_series, t_series = \
    #         simulate_xs_with_EN(model_f, model_eps, x_init, s_init, dt, length=length, stop_threshold=-1)

    #     SS.append(np.c_[t_series, x_series, s_series])
    #     plt.plot(t_series, x_series, label=seed)
    # plt.legend()
    # np.savez('./figures/Saddle_low_simulations.npz', *SS)
    