#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat May 21 13:37:35 2022

@author: dliu
"""

import sys 
sys.path.append("..") 
import numpy as np
import matplotlib.pyplot as plt
import torch
import torch.autograd as autograd

from utils import get_dataset
from misc import parameters


device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
params = parameters(data_type='CGL', n_trainset=1, kx=1, ks=10, lr=3e-5)


def flat(x):
    m = x.shape[0]
    return [x[i] for i in range(m)]
def Du(t,u):
    u_t = autograd.grad(flat(u), t, create_graph=True, allow_unused=True)[0]
    return u_t


def simulate_GAN(gen, x1, s1, diff_x, dt_x, idx=0, n_time=660):
    batch_size, step=1, 1
    
    sigma1_batch = torch.FloatTensor(x1[[idx]]).to(device)
    noise = torch.randn(batch_size*1, 2).to(device)
    
    gen_sigma = x1[[idx]]
    real_sigma = x1[[idx]]
    real_x = s1[[idx]]
    
    gen_f, real_f = [], []
    tt_ = [0]
    for t in range(n_time):
        # For each batch
        tt_batch = torch.ones(batch_size,1).to(device)
        x_batch = torch.FloatTensor(s1[[idx+t*step]]).to(device)
        sigma2_batch = torch.FloatTensor(x1[[idx+(t+1)*step],:]).to(device) #current x generate next sigma
        # sigma2_batch = sigma2_batch+torch.randn(sigma2_batch.shape).to(device)*.1
        f_batch = torch.FloatTensor(diff_x[[idx+(t+1)*step],:])
    
        noisev = torch.cat((tt_batch, x_batch, sigma1_batch, noise), 1).to(device)
        noisev.requires_grad=True
    
        fake_sigma2  = gen(noisev)
        fout1 = Du(noisev, fake_sigma2[:,0])
        fout2 = Du(noisev, fake_sigma2[:,1])
        fout = torch.cat((fout1[:,[0]], fout2[:,[0]]),1).cpu().detach().numpy()
        gen_f.append(fout.flatten())
        real_f.append(f_batch.numpy().flatten())
    
        gen_sigma = np.r_[gen_sigma, fake_sigma2.detach().cpu().numpy()]
        # gen_sigma.extend(fake_sigma2.detach().cpu().numpy())
        real_sigma = np.r_[real_sigma, sigma2_batch.detach().cpu().numpy()]
        real_x = np.r_[real_x, x_batch.detach().cpu().numpy()]
        
        sigma1_batch = fake_sigma2.detach()
    
        tt_.append(dt_x[idx+t*step].item())

    gen_f = np.array(gen_f)
    real_f = np.array(real_f)
    
    gen_sigma = gen_sigma[:-1,:]
    real_sigma = real_sigma[:-1,:]
    tt = np.cumsum(tt_)[:-1]

    return gen_sigma, real_sigma, gen_f, real_f, tt


if __name__=="__main__":
    
    ##### simulate x with given sigma by PI-CGAN #####
    from model import generator_hopf
    gen = generator_hopf().to(device)
    
    gen.load_state_dict(torch.load(params.model_gen_path))
    
    data_test_pathes = params.data_pathes[params.n_trainset:params.n_trainset+1]
    ### load data ###
    x_lower_bound = params.x_lower_bound
    kx = params.kx
    ks = params.ks
    x1, x2, s1, s2, diff_x, diff_s, dt_x, dt_s = \
        get_dataset(data_test_pathes, x_lower_bound=x_lower_bound, kx=kx, ks=ks, resample=False)
    
    mse1_list, mse2_list, msef1_list, msef2_list = [], [], [], []
    mse_list, msef_list = [], []
    length = 600
    idx = np.random.randint(x1.shape[0]-600)
    gen_sigma, real_sigma, gen_f, real_f, tt = simulate_GAN(gen, x1, s1, diff_x, dt_x, idx, n_time=length)
    
    
    
    mse1 = np.average((gen_sigma[:,0]-real_sigma[:,0])**2)
    mse2 = np.average((gen_sigma[:,1]-real_sigma[:,1])**2)
    msef1 = np.average((gen_f[:, 0]-real_f[:, 0])**2)
    msef2 = np.average((gen_f[:, 1]-real_f[:, 1])**2)
    
    fig, axes = plt.subplots(2,2, figsize = [20,15])
    axes = axes.flatten()
    axes[0].plot(tt, gen_sigma[:,0], linewidth=.6, label=r'$X_1$ generated by $G_{\theta}$')
    axes[0].plot(tt, real_sigma[:,0], linewidth=.6, label='$X_1$ real')
    axes[0].plot([], [], ' ', label="MSE={:.2e}".format(mse1))
    axes[0].set_ylim(-3,1.1)
    axes[0].set_xlabel('t')
    axes[0].legend(loc='lower right')
    
    axes[1].plot(tt, gen_f[:,0], linewidth=.6, label=r"$X_1'$ generated by $\frac{\partial G_{\theta}}{\partial t}$")
    axes[1].plot(tt, real_f[:,0],  linewidth=.6, label="$X_1'$ numerical")
    axes[1].plot([], [], ' ', label="MSE={:.2e}".format(msef1))
    axes[1].set_ylim(-.8,.4)
    axes[1].set_xlabel('t')
    axes[1].legend(loc='lower right')
    
    axes[2].plot(tt, gen_sigma[:,1], linewidth=.6, label=r'$X_2$ generated by $G_{\theta}$')
    axes[2].plot(tt, real_sigma[:,1], linewidth=.6, label='$X_2$ real')
    axes[2].plot([], [], ' ', label="MSE={:.2e}".format(mse2))
    axes[2].set_ylim(-2.2,1.1)
    axes[2].set_xlabel('t')
    axes[2].legend(loc='lower right')
    
    axes[3].plot(tt, gen_f[:,1], linewidth=.6, label=r"$X_2'$ generated by $\frac{\partial G_{\theta}}{\partial t}$")
    axes[3].plot(tt, real_f[:,1],  linewidth=.6, label="$X_2'$ numerical")
    axes[3].plot([], [], ' ', label="MSE={:.2e}".format(msef2))
    axes[3].set_ylim(-.8,.4)
    axes[3].set_xlabel('t')
    axes[3].legend(loc='lower right')
    
    fig.suptitle('Simulation by PI-CGAN')
    fig.savefig('./figures/CGL_simulation_with_given_sigma_GAN.png', bbox_inches='tight')
    
    
    
    
